sonar.projectKey=hammad0-dev_End-to-End-Secure-DevSecOps-Platform-with-Docker-Kubernetes-Infrastructure-as-Code
sonar.organization=hammad0-dev


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=End-to-End-Secure-DevSecOps-Platform-with-Docker-Kubernetes-Infrastructure-as-Code
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8