pipeline {
  agent { label 'docker' }
  options {
    timeout(time: 60, unit: 'MINUTES')
    timestamps()
    ansiColor('xterm')
  }
  environment {
    REGISTRY = "ghcr.io/securebank"
    SONAR_TOKEN = credentials('sonar-token')
    COSIGN_PRIVATE_KEY = credentials('cosign-key')
  }
  stages {
    stage('Lint & Unit Test') {
      steps {
        sh 'pip install -e src/shared[dev]'
        sh 'ruff check src/'
        sh 'bandit -q -r src/ -lll -iii'
        sh 'pytest -q src/shared/tests'
      }
    }
    stage('SAST') {
      steps { sh 'sonar-scanner -Dsonar.login=$SONAR_TOKEN' }
    }
    stage('SCA') {
      steps { sh 'pip-audit -r src/shared/pyproject.toml || true' }
    }
    stage('Secrets') {
      steps { sh 'gitleaks detect --no-banner --redact' }
    }
    stage('Build & Image Scan') {
      matrix {
        axes {
          axis { name 'SVC'
                 values 'auth-service','account-service','transaction-service',
                        'fraud-detection-service','notification-service','api-gateway' }
        }
        stages {
          stage('build') {
            steps {
              sh "docker build -f docker/${SVC}.Dockerfile -t ${REGISTRY}/${SVC}:${BUILD_NUMBER} ."
              sh "trivy image --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed ${REGISTRY}/${SVC}:${BUILD_NUMBER}"
              sh "cosign sign --key env://COSIGN_PRIVATE_KEY ${REGISTRY}/${SVC}:${BUILD_NUMBER}"
              sh "docker push ${REGISTRY}/${SVC}:${BUILD_NUMBER}"
            }
          }
        }
      }
    }
    stage('Deploy to Dev') {
      when { branch 'main' }
      steps { sh 'helm upgrade --install securebank ./k8s/helm -n securebank-app --create-namespace --values k8s/helm/values-dev.yaml' }
    }
    stage('DAST — ZAP Baseline') {
      when { branch 'main' }
      steps {
        sh 'docker run --rm -v $PWD:/zap/wrk owasp/zap2docker-stable zap-baseline.py -t https://api.securebank.local -r zap-baseline.html || true'
        archiveArtifacts artifacts: 'zap-baseline.html', fingerprint: true
      }
    }
  }
  post {
    always {
      junit allowEmptyResults: true, testResults: '**/junit*.xml'
      cleanWs()
    }
    failure { slackSend channel: '#securebank-ci', color: 'danger', message: "❌ Build #${BUILD_NUMBER} failed" }
    success { slackSend channel: '#securebank-ci', color: 'good',   message: "✅ Build #${BUILD_NUMBER} passed" }
  }
}
