sonar.projectKey=securebank
sonar.projectName=SecureBank
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=**/tests/**,**/migrations/**
sonar.tests=src
sonar.test.inclusions=**/tests/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.bandit.reportPaths=bandit-report.json
sonar.qualitygate.wait=true
